### PR TITLE
loosen bounds

### PR DESCRIPTION
**Pull request by OkonSamuel**
At the moment, `ScikitLearn.jl` limits the conda sklearn version to <1.1 for Linux users. This was due to the libstdxx issue with Julia, which has long been fixed for later Julia versions `>=v0.8.4`. 
This PR proposes loosens the bounds of the conda sklearn version. It also makes sure that compatible conda sklearn versions are installed across Windows, macOS, and linux platforms. At the moment this corresponds to version `>=1.2, <1.3` (This was chosen, since a minor release may contain several code deprecations). We could change this bound when python sklearn releases a new minor release, which doesn't happen often.

cc. @cstjean, @tylerjthomas9 @ablaom

### CODE REVIEW

**Review by cstjean — APPROVED** [review]
👍

**Comment by cstjean** [comment]
If the docs CI fails unrelatedly, feel free to merge anyway...

**Comment by cstjean** [comment]
Might be worth squash merging when the time comes...

**Comment by OkonSamuel** [comment]
> Might be worth squash merging when the time comes...

Sure. I planned on doing that

**Comment by ablaom** [comment]
@OkonSamuel Do you mean to leave this as draft or are you ready for review?

**Comment by OkonSamuel** [comment]
> @OkonSamuel Do you mean to leave this as draft or are you ready for review?

@ablaom Okay. I'm ready for a review.

**Comment by ablaom** [comment]
I can confirm that `@sk_import` appears to work on macOS with PYTHON="", julia=1.6.5. Tests fail, but this appears to be orthogonal to the objective of the present PR (the same test fails under "master"). 

For the record details are below:

<details>

```
Testing ../examples/Pipeline_PCA_Logistic.ipynb
WARNING: replacing module Testing.
Notebook examples: Error During Test at /Users/anthony/Julia/ScikitLearn/test/runtests.jl:63
  Got exception outside of a @test
  LoadError: PyError ($(Expr(:escape, :(ccall(#= /Users/anthony/.julia/packages/PyCall/twYvK/src/pyfncall.jl:43 =# @pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, pyargsptr, kw))))) <class 'AttributeError'>
  AttributeError("'str' object has no attribute 'decode'")
    File "/Users/anthony/anaconda2/envs/py37/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py", line 1601, in fit
      for class_, warm_start_coef_ in zip(classes_, warm_start_coef))
    File "/Users/anthony/anaconda2/envs/py37/lib/python3.7/site-packages/joblib/parallel.py", line 1085, in __call__
      if self.dispatch_one_batch(iterator):
    File "/Users/anthony/anaconda2/envs/py37/lib/python3.7/site-packages/joblib/parallel.py", line 901, in dispatch_one_batch
      self._dispatch(tasks)
    File "/Users/anthony/anaconda2/envs/py37/lib/python3.7/site-packages/joblib/parallel.py", line 819, in _dispatch
      job = self._backend.apply_async(batch, callback=cb)
    File "/Users/anthony/anaconda2/envs/py37/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
      result = ImmediateResult(func)
    File "/Users/anthony/anaconda2/envs/py37/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 597, in __init__
      self.results = batch()
    File "/Users/anthony/anaconda2/envs/py37/lib/python3.7/site-packages/joblib/parallel.py", line 289, in __call__
      for func, args, kwargs in self.items]
    File "/Users/anthony/anaconda2/envs/py37/lib/python3.7/site-packages/joblib/parallel.py", line 289, in <listcomp>
      for func, args, kwargs in self.items]
    File "/Users/anthony/anaconda2/envs/py37/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py", line 940, in _logistic_regression_path
      extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
    File "/Users/anthony/anaconda2/envs/py37/lib/python3.7/site-packages/sklearn/utils/optimize.py", line 243, in _check_optimize_result
      ).format(solver, result.status, result.message.decode("latin1"))
  
  Stacktrace:
    [1] pyerr_check
      @ ~/.julia/packages/PyCall/twYvK/src/exception.jl:75 [inlined]
    [2] pyerr_check
      @ ~/.julia/packages/PyCall/twYvK/src/exception.jl:79 [inlined]
    [3] _handle_error(msg::String)
      @ PyCall ~/.julia/packages/PyCall/twYvK/src/exception.jl:96
    [4] macro expansion
      @ ~/.julia/packages/PyCall/twYvK/src/exception.jl:110 [inlined]
    [5] #107
      @ ~/.julia/packages/PyCall/twYvK/src/pyfncall.jl:43 [inlined]
    [6] disable_sigint
      @ ./c.jl:458 [inlined]
    [7] __pycall!
      @ ~/.julia/packages/PyCall/twYvK/src/pyfncall.jl:42 [inlined]
    [8] _pycall!(ret::PyCall.PyObject, o::PyCall.PyObject, args::Tuple{Matrix{Float64}, Vector{Int64}}, nargs::Int64, kw::Ptr{Nothing})
      @ PyCall ~/.julia/packages/PyCall/twYvK/src/pyfncall.jl:29
    [9] _pycall!(ret::PyCall.PyObject, o::PyCall.PyObject, args::Tuple{Matrix{Float64}, Vector{Int64}}, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ PyCall ~/.julia/packages/PyCall/twYvK/src/pyfncall.jl:11
   [10] (::PyCall.PyObject)(::Matrix{Float64}, ::Vararg{Any, N} where N; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ PyCall ~/.julia/packages/PyCall/twYvK/src/pyfncall.jl:86
   [11] (::PyCall.PyObject)(::Matrix{Float64}, ::Vararg{Any, N} where N)
      @ PyCall ~/.julia/packages/PyCall/twYvK/src/pyfncall.jl:86
   [12] fit!(::PyCall.PyObject, ::Matrix{Float64}, ::Vararg{Any, N} where N; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ ScikitLearn.Skcore ~/Julia/ScikitLearn/src/Skcore.jl:102
   [13] fit!(::PyCall.PyObject, ::Matrix{Float64}, ::Vector{Int64})
      @ ScikitLearn.Skcore ~/Julia/ScikitLearn/src/Skcore.jl:102
   [14] fit!(pip::Pipeline, X::Matrix{Float64}, y::Vector{Int64})
      @ ScikitLearn.Skcore ~/Julia/ScikitLearn/src/pipeline.jl:70
   [15] _fit_and_score(estimator::Pipeline, X::Matrix{Float64}, y::Vector{Int64}, scorer::Function, train::Vector{Int64}, test::Vector{Int64}, verbose::Int64, parameters::Dict{Symbol, Any}, fit_params::Dict{Symbol, Any}; return_train_score::Bool, return_parameters::Bool, error_score::String)
      @ ScikitLearn.Skcore ~/Julia/ScikitLearn/src/cross_validation.jl:574
   [16] (::ScikitLearn.Skcore.var"#101#102"{GridSearchCV, Pipeline, Matrix{Float64}, Vector{Int64}, Dict{Any, Any}})(::Tuple{Vector{Int64}, Vector{Int64}})
      @ ScikitLearn.Skcore ./none:0
   [17] iterate
      @ ./generator.jl:47 [inlined]
   [18] collect(itr::Base.Generator{Vector{Tuple{Vector{Int64}, Vector{Int64}}}, ScikitLearn.Skcore.var"#101#102"{GridSearchCV, Pipeline, Matrix{Float64}, Vector{Int64}, Dict{Any, Any}}})
      @ Base ./array.jl:681
   [19] fit_cv_rotations(self::GridSearchCV, estimator::Pipeline, X::Matrix{Float64}, y::Vector{Int64}, parameters::Dict{Any, Any}, cv::Vector{Tuple{Vector{Int64}, Vector{Int64}}})
      @ ScikitLearn.Skcore ~/Julia/ScikitLearn/src/grid_search.jl:244
   [20] _fit!(self::GridSearchCV, X::Matrix{Float64}, y::Vector{Int64}, parameter_iterable::ScikitLearn.Skcore.ParameterGrid)
      @ ScikitLearn.Skcore ~/Julia/ScikitLearn/src/grid_search.jl:281
   [21] fit!(self::GridSearchCV, X::Matrix{Float64}, y::Vector{Int64})
      @ ScikitLearn.Skcore ~/Julia/ScikitLearn/src/grid_search.jl:563
   [22] top-level scope
      @ ~/Julia/ScikitLearn/examples/Pipeline_PCA_Logistic.ipynb:In[2]:35
   [23] eval
      @ ./boot.jl:360 [inlined]
   [24] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
      @ Base ./loading.jl:1116
   [25] include_string
      @ ./loading.jl:1126 [inlined]
   [26] my_include_string(m::Module, s::String, path::String, prev::String, softscope::Bool)
      @ NBInclude ~/.julia/packages/NBInclude/MxvbF/src/NBInclude.jl:30
   [27] #2
      @ ~/.julia/packages/NBInclude/MxvbF/src/NBInclude.jl:93 [inlined]
   [28] task_local_storage(body::NBInclude.var"#2#3"{Bool, Module, String, String, String, String}, key::Symbol, val::Bool)
      @ Base ./task.jl:281
   [29] nbinclude(m::Module, path::String; renumber::Bool, counters::UnitRange{Int64}, regex::Regex, anshook::typeof(identity), softscope::Bool)
      @ NBInclude ~/.julia/packages/NBInclude/MxvbF/src/NBInclude.jl:92
   [30] nbinclude(m::Module, path::String)
      @ NBInclude ~/.julia/packages/NBInclude/MxvbF/src/NBInclude.jl:65
   [31] top-level scope
      @ ~/Julia/ScikitLearn/test/runtests.jl:56
   [32] eval
      @ ./boot.jl:360 [inlined]
   [33] (::var"#run_examples#1"{Vector{String}})()
      @ Main ~/Julia/ScikitLearn/test/runtests.jl:54
   [34] macro expansion
      @ ~/Julia/ScikitLearn/test/runtests.jl:64 [inlined]
   [35] macro expansion
      @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [36] macro expansion
      @ ~/Julia/ScikitLearn/test/runtests.jl:64 [inlined]
   [37] macro expansion
      @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [38] top-level scope
      @ ~/Julia/ScikitLearn/test/runtests.jl:12
   [39] include(fname::String)
      @ Base.MainInclude ./client.jl:444
   [40] top-level scope
      @ none:6
   [41] eval
      @ ./boot.jl:360 [inlined]
   [42] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:261
   [43] _start()
      @ Base ./client.jl:485
  in expression starting at /Users/anthony/Julia/ScikitLearn/examples/Pipeline_PCA_Logistic.ipynb:In[2]:35
```
</details>

File: README.md [hunk 1]
```diff
@@ -35,6 +35,15 @@ To install ScikitLearn.jl, type `]add ScikitLearn` at the REPL.
...
 
+## Known issue
+
+On Linux builds, importing python models via `@sk_import` is known to fail for Julia v<0.8.4 when the `PYTHON` enviroment variable from `PyCall.jl` is set to `""` or `conda`. This is becuase the version libstdcxx loaded by Julia v<0.8.4 isn't compatible with the version of scikit-learn installed via Conda.
+The easiest and recommended way to resolve this is to upgrade to Julia v>=1.8.4. If you must stick with your current julia version you can also resolve this issue by pre-appending your system's `LD_LIBRARY_PATH` enviroment variable as shown below
+```bash
+ROOT_ENV=`julia -e "using Conda; print(Conda.ROOTENV)`
+export LD_LIBRARY_PATH=$ROOT_ENV"/lib":$LD_LIBRARY_PATH
+```
+
```
Comment (ablaom) [inline README.md:46]: This is a very clear explanation, and this seems like the right approach for dealing with the older Julia versions.

**Comment by OkonSamuel** [comment]
> 

The tests for 1.6 were run with the current long term release for Julia, which is `1.6.7`. I suggest trying the code again with Julia `v1.6.7`

File: src/Skcore.jl [hunk 2]
```diff
@@ -166,55 +166,66 @@ function import_sklearn()
...
-                    #force reinstall of scikit-learn replacing any previous mkl version
-                    Conda.add("scikit-learn")
-                    Conda.add("openblas")
-                    Conda.add("llvm-openmp", channel = "conda-forge")
-                    mkl_checked = true
-                catch
-                    mkl_checked = true
-                end   
+                catch err
+                    ## This block is reached when `mkl` pkg isn't installed.
```
Comment (ablaom) [inline src/Skcore.jl:186]: I'm puzzled  as to why this catch block contains no code.

**Comment by ablaom** [comment]
Mmm. I'm getting the same error for julia 1.8

```julia
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 12 × Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 5 on 12 virtual cores
Environment:
  JULIA_LTS_PATH = /Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia
  JULIA_PATH = /Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia
  JULIA_EGLOT_PATH = /Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia
  JULIA_NUM_THREADS = 5
  DYLD_LIBRARY_PATH = /usr/local/homebrew/Cellar/libomp/9.0.1/lib/
  JULIA_NIGHTLY_PATH = /Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia
```

File: src/Skcore.jl (hunk 2 above)
Comment (OkonSamuel) [reply src/Skcore.jl:186]: Yeah, that's deliberate. I didn't wan't the try block to throw any error yet. I guess I should use a `try ... finally` there

**Comment by ablaom** [comment]
okay it seems my non-julia conda install of python is being used, despite the PYTHON flag.  i'll investigate

**Comment by OkonSamuel** [comment]
> okay it seems my non-julia conda install of python is being used, despite the PYTHON flag. i'll investigate

after changing the `PYTHON` enviroment variable. You will need to run`] build PyCall`

**Comment by ablaom** [comment]
@OkonSamuel Thanks, my bad. Both 1.6 and 1.8 pass tests locally on my Mac, after I remember to `build` after changing my env 😳

**Review by ablaom — COMMENTED** [review]
Thanks indeed @OkonSamuel for sorting this out. It certainly looks like an improvement, although I'm probably not the best qualified to review. If @cstjean is happy, I think this should go ahead.

**Comment by cstjean** [comment]
Thank you for checking @ablaom ! I trust @OkonSamuel on this one, LGTM. Merge?

File: src/Skcore.jl (hunk 2 above)
Comment (ablaom) [reply src/Skcore.jl:190]: all good
